spring:
  application:
    name: smartbudget
  datasource:
    url: jdbc:postgresql://147.45.140.254/smartbudget
    username: shiae
    password: shiaeshiae
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
smartbudget:
  app:
    jwtSecret: YZ0UwB+IYtL5/u3+gATe4uf+FxkhU68yBKKdic0tYxKD7X9wYzGTmf3ZlrftVLNP
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true